import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("playwright");
const browser = await chromium.launch({ args: ["--use-gl=angle", "--use-angle=metal", "--enable-gpu", "--ignore-gpu-blocklist", "--autoplay-policy=no-user-gesture-required"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, colorScheme: "dark" });
await page.route("**/api/auth/me", (r) => r.fulfill({ json: { databaseConfigured: true, user: { id: "u1", email: "s@x.com", username: "sana", onboarded: true, needsLearnerProfile: false, needsPreferences: false, hasPassword: true, providers: [] }, profile: { displayName: "Sana", age: 15, accessibility: "none", reducedMotion: null, captions: null, slowerPace: null, simplerLanguage: null, notes: null, learner: null, updatedAt: "" } } }));
await page.goto("http://localhost:3000/player-preview", { waitUntil: "domcontentloaded", timeout: 120000 });
await page.waitForTimeout(16000);
const flyer = page.locator('[role="img"][aria-label="Aria"]');
const where = async () => { const b = await flyer.boundingBox(); return b ? `${Math.round(b.x)},${Math.round(b.y)} ${Math.round(b.width)}x${Math.round(b.height)}` : "none"; };
await page.waitForTimeout(800);
console.log("before start:", await where());
await page.screenshot({ path: "/tmp/aria-place-stage0.png" });
await page.getByRole("button", { name: /^(Play|Start)/i }).first().click();
await page.waitForTimeout(700);
console.log("just after start:", await where());
await page.screenshot({ path: "/tmp/aria-place-stage1.png" });
await page.waitForTimeout(8000);
console.log("board:", await where());
const next = page.getByRole("button", { name: /next/i }).first();
await next.click();
await page.waitForTimeout(1600);
console.log("transition 1.6s:", await where());
await page.screenshot({ path: "/tmp/aria-place-stage2.png" });
await page.waitForTimeout(1500);
console.log("transition 3.1s:", await where());
await page.screenshot({ path: "/tmp/aria-place-stage3.png" });
await page.waitForTimeout(6000);
console.log("board 2:", await where());
await page.screenshot({ path: "/tmp/aria-place-beside2.png" });
await page.getByRole("button", { name: /ask/i }).first().click();
await page.waitForTimeout(1500);
console.log("sheet:", await where());
await page.screenshot({ path: "/tmp/aria-place-sheet.png" });
await browser.close();
