import type { Metadata } from "next";
import { Geist, Geist_Mono, Kalam } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Hand-drawn marker-style font — this is what makes headings/labels/bullets read as
// "sketched" rather than "typed," with zero drawing logic of our own.
const sketchFont = Kalam({
  variable: "--font-sketch",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sketchFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={{ background: "#f4f1ea" }}>{children}</body>
    </html>
  );
}
