import type { CampusPerson, CampusRoom } from "./types";

export const CAMPUS_ROOMS: CampusRoom[] = [
  {
    id: "atrium",
    shortName: "Atrium",
    name: "ARIA Welcome Atrium",
    subject: "Campus hub",
    description: "A daylight-filled orientation hall with reception, schedule board, and direct routes to every learning space.",
    accommodation: "Step-free navigation, direct travel, semantic landmarks, and staffed help desk.",
    zone: "atrium",
    position: [0, 0, 15.5],
    camera: [0, 5.8, 15],
    target: [0, 1.6, 5],
    accent: "#c84f40",
    capacity: 42,
    occupied: 18,
    nextSession: "Campus orientation · now",
  },
  {
    id: "general",
    shortName: "Studio 101",
    name: "General Learning Studio",
    subject: "Mathematics · Science · Humanities",
    description: "A flexible seminar classroom with tiered sightlines and a wall-scale interactive teaching board.",
    accommodation: "Movable seating, companion spaces, adjustable board focus, and multiple participation modes.",
    zone: "classroom",
    position: [-11.4, 0, -6],
    camera: [-10, 3.05, 0.8],
    target: [-10, 2.3, -9.2],
    accent: "#176f73",
    capacity: 24,
    occupied: 17,
    nextSession: "Calculus foundations · 10:30",
  },
  {
    id: "focus",
    shortName: "Focus Lab",
    name: "Focus & Executive Function Lab",
    subject: "Structured study",
    description: "A low-distraction classroom with clear task zones, calm surfaces, and predictable visual hierarchy.",
    accommodation: "Reduced ambient movement, visual timers, chunked wayfinding, and optional quiet-world mode.",
    zone: "classroom",
    position: [-11.4, 0, -17.4],
    camera: [0, 3.05, 0.8],
    target: [0, 2.3, -9.2],
    accent: "#597b50",
    capacity: 16,
    occupied: 9,
    nextSession: "Study planning · 11:00",
  },
  {
    id: "sensory",
    shortName: "Calm Studio",
    name: "Sensory-Calm Learning Studio",
    subject: "Low-stimulation learning",
    description: "A softly lit studio with generous spacing, retreat seating, and controlled sensory load.",
    accommodation: "Dimmer environment, low animation, no forced proximity, and immediate safe-place return.",
    zone: "classroom",
    position: [11.4, 0, -17.4],
    camera: [10, 3.05, 0.8],
    target: [10, 2.3, -9.2],
    accent: "#7e657b",
    capacity: 12,
    occupied: 6,
    nextSession: "Biology in patterns · 11:30",
  },
  {
    id: "vision",
    shortName: "Vision Access",
    name: "Vision Access Studio",
    subject: "Multisensory instruction",
    description: "A high-legibility room where every spatial destination and interactive object has a text equivalent.",
    accommodation: "High contrast, large labels, audio-ready landmarks, direct travel, and screen-reader room map.",
    zone: "classroom",
    position: [11.4, 0, -6],
    camera: [-10, 3.05, 17.2],
    target: [-10, 2.3, 8.8],
    accent: "#b58318",
    capacity: 14,
    occupied: 8,
    nextSession: "Data through sound · 12:00",
  },
  {
    id: "communication",
    shortName: "Communication",
    name: "Communication Access Studio",
    subject: "Language & discussion",
    description: "A conversation classroom designed around clear turn-taking and equal voice, text, and visual participation.",
    accommodation: "Caption-first layout, visual speaker cues, raised-hand states, mono audio, and typed participation.",
    zone: "classroom",
    position: [11.4, 0, -28],
    camera: [10, 3.05, 17.2],
    target: [10, 2.3, 8.8],
    accent: "#356aa0",
    capacity: 18,
    occupied: 12,
    nextSession: "World literature · 12:30",
  },
  {
    id: "commons",
    shortName: "Commons",
    name: "Student Commons",
    subject: "Conversation & peer learning",
    description: "An informal social space for study groups, chance encounters, club tables, and quiet booths.",
    accommodation: "Visible availability status, quiet booths, wide routes, and opt-in proximity interaction.",
    zone: "commons",
    position: [0, 0, 3.6],
    camera: [18, 5, 15],
    target: [18, 1.4, 8],
    accent: "#c55d34",
    capacity: 32,
    occupied: 14,
    nextSession: "Peer study circle · 13:00",
  },
  {
    id: "library",
    shortName: "Library",
    name: "Research Library",
    subject: "Independent learning",
    description: "A quiet reading room with collaborative tables, resource terminals, and faculty office-hour nooks.",
    accommodation: "Silent zone, individual study lighting, simplified navigation, and seated access at every desk.",
    zone: "library",
    position: [0, 0, -39],
    camera: [-18, 5, 15],
    target: [-18, 1.4, 8],
    accent: "#6a4f3a",
    capacity: 30,
    occupied: 11,
    nextSession: "Research clinic · 14:00",
  },
  {
    id: "wellness",
    shortName: "Wellness",
    name: "Wellness & Reset Room",
    subject: "Private reset space",
    description: "A no-obligation decompression room that can be reached immediately from anywhere on campus.",
    accommodation: "Safe-place shortcut, muted activity, session timer, and no social connection requests.",
    zone: "wellness",
    position: [-11.4, 0, -28],
    camera: [18, 4.2, 1],
    target: [18, 1.4, -5],
    accent: "#477c69",
    capacity: 8,
    occupied: 2,
    nextSession: "Always open",
  },
];

export const CAMPUS_PEOPLE: CampusPerson[] = [
  { id: "teacher", name: "Dr. Mira Chen", role: "Gemini Live teacher", status: "teaching", position: [-8.1, 0, -8.2], palette: ["#2d4249", "#d5a37d", "#f1eee8"], activity: "teach" },
  { id: "student-a", name: "Aaliyah", role: "Computer science", status: "available", position: [-11.5, 0, -2.2], palette: ["#7d4037", "#8c5d3f", "#d8b08a"], activity: "study" },
  { id: "student-b", name: "Noah", role: "Mathematics", status: "focused", position: [-8.8, 0, -1.4], palette: ["#315e68", "#3f2f2d", "#c88f6b"], activity: "study" },
  { id: "guide", name: "Samira", role: "Campus guide", status: "available", position: [2.6, 0, 6.5], palette: ["#a95042", "#332824", "#b8795c"], activity: "talk" },
  { id: "student-c", name: "Leo", role: "Design studies", status: "available", position: [17.2, 0, 9.5], palette: ["#3b6c56", "#4b342c", "#e2b997"], activity: "talk" },
  { id: "student-d", name: "Inez", role: "Literature", status: "focused", position: [-17.4, 0, 7], palette: ["#74516d", "#241d1a", "#9f6b50"], activity: "study" },
];
