import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { Resvg } from "@resvg/resvg-js";
import { boardToSvg } from "@/lib/boardSvgSerializer";
import type { Beat } from "@/lib/lessonContent";

/**
 * Export a played lecture as a revision PDF: one page per beat with the board image on top and the
 * spoken transcript beneath it. Reuses the same board→SVG serializer the vision critic uses
 * (lib/boardSvgSerializer.ts) plus @resvg/resvg-js to rasterize — no headless browser.
 *
 * Beats whose visual is a sandboxed React animation can't be serialized to SVG (it's live code), so
 * those pages carry the title + transcript and say the visual was an animation.
 */

const PAGE_W = 792; // US Letter landscape — matches the 1000x560 board aspect better than portrait
const PAGE_H = 612;
const MARGIN = 36;

function wrap(text: string, max: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > max) {
      if (line) lines.push(line.trim());
      line = w;
    } else {
      line = `${line} ${w}`;
    }
  }
  if (line.trim()) lines.push(line.trim());
  return lines;
}

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}));
  const topic = typeof body.topic === "string" ? body.topic.trim() : "Lesson";
  const beats: Beat[] = Array.isArray(body.beats) ? body.beats : [];
  if (!beats.length) return NextResponse.json({ error: "beats are required" }, { status: 400 });

  try {
    const pdf = await PDFDocument.create();
    pdf.setTitle(topic);
    const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const body_ = await pdf.embedFont(StandardFonts.Helvetica);

    // Cover
    const cover = pdf.addPage([PAGE_W, PAGE_H]);
    cover.drawText("Lesson transcript", { x: MARGIN, y: PAGE_H - MARGIN - 18, size: 12, font: body_, color: rgb(0.45, 0.45, 0.5) });
    wrap(topic, 46).slice(0, 3).forEach((line, i) => {
      cover.drawText(line, { x: MARGIN, y: PAGE_H - MARGIN - 60 - i * 30, size: 24, font: bold, color: rgb(0.1, 0.12, 0.15) });
    });
    cover.drawText(`${beats.length} sections · generated by Aria`, {
      x: MARGIN, y: MARGIN, size: 10, font: body_, color: rgb(0.5, 0.5, 0.55),
    });

    for (const [i, beat] of beats.entries()) {
      const page = pdf.addPage([PAGE_W, PAGE_H]);
      let y = PAGE_H - MARGIN;

      // Heading
      const heading = `${i + 1}. ${beat.title ?? ""}`.trim();
      page.drawText(heading.slice(0, 90), { x: MARGIN, y: y - 14, size: 14, font: bold, color: rgb(0.1, 0.12, 0.15) });
      y -= 34;

      // Board image (if serializable)
      const isAnimation = (beat.draw?.ops ?? []).some((op) => op.kind === "reactAnimation");
      const svg = isAnimation ? "" : boardToSvg(beat.draw);
      if (svg) {
        try {
          const png = new Resvg(svg, { fitTo: { mode: "width", value: 1400 } }).render().asPng();
          const img = await pdf.embedPng(png);
          const maxW = PAGE_W - MARGIN * 2;
          const h = (img.height / img.width) * maxW;
          page.drawImage(img, { x: MARGIN, y: y - h, width: maxW, height: h });
          y -= h + 18;
        } catch {
          /* fall through to text-only page */
        }
      } else if (isAnimation) {
        page.drawText("[ animated board — see the lesson for the motion ]", {
          x: MARGIN, y: y - 12, size: 10, font: body_, color: rgb(0.5, 0.5, 0.55),
        });
        y -= 28;
      }

      // Transcript
      const script = (beat.script ?? "").trim();
      if (script) {
        page.drawText("Transcript", { x: MARGIN, y: y - 11, size: 9, font: bold, color: rgb(0.45, 0.45, 0.5) });
        y -= 24;
        for (const line of wrap(script, 108)) {
          if (y < MARGIN + 12) break; // don't spill off the page
          page.drawText(line, { x: MARGIN, y, size: 9.5, font: body_, color: rgb(0.2, 0.22, 0.26) });
          y -= 13;
        }
      }
    }

    const bytes = await pdf.save();
    const safe = (topic || "lesson").replace(/[^\w\- ]+/g, "").trim().replace(/\s+/g, "-").slice(0, 60) || "lesson";
    return new Response(new Uint8Array(bytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safe}.pdf"`,
      },
    });
  } catch (err) {
    console.error(`[export-pdf] failed: ${err instanceof Error ? err.message : "error"}`);
    return NextResponse.json({ error: "Could not build the PDF." }, { status: 500 });
  }
}
